esm: pin repositories to a higher priority using a static file
canonical/ubuntu-pro-client pull request #2664
Opened 2023-07-21 17:26 UTC by renanrodrigo

note: this PR is one of the alternatives to pinning ESM. The other alternative is #2663 . Please merge one of them and discard the other.

## Why is this needed?
This PR solves all of our problems because it 
Fixes: #2580
context is provided in the issue and the internal spec

## Test Steps
Run CI

## Checklist
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [x] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?
 - [x] Yes - basak or panlinux
 - [ ] No

2023-07-25 08:01 UTC, cpaelzer requested changes
Some discussions and some minor requests to adapt.

2023-07-31 13:46 UTC, orndorffgrant commented on preferences.d/ubuntu-pro-preferences
> +Package: *
Discussed and standup and decided to split into separate files

2023-07-31 13:52 UTC, orndorffgrant commented on preferences.d/ubuntu-pro-preferences
> +Package: *
@renanrodrigo will add test to cover the upgrade scenario of having fips enabled and renaming the file to ubuntu-pro-fips - and making sure conffile prompts only happen when they should.

2023-08-15 20:33 UTC, lucasmoura commented
Closing this one as we already merged #2681

2023-08-15 20:33 UTC, closed without merging

2023-08-15 21:45 UTC, renanrodrigo commented
@renanrodrigo just so I don't forget to look at Christian's comments again