docs: update Pro manpage
canonical/ubuntu-pro-client pull request #3226
Opened 2024-07-25 17:19 UTC by lucasmoura

## Why is this needed?
Update the commands listed in the Pro manpage while also updating the services we support there as well

## Test Steps
Check if the `man pro` outputs the new manpage

---

- [ ] *(un)check this to re-run the checklist action*

2024-07-25 18:17 UTC, dheyay requested changes
Thanks for this @lucasmoura!

Left a few comments with suggested changes (really small ones), otherwise the content looks great

2024-07-25 18:17 UTC, dheyay commented on ubuntu-advantage.1
> +If attached, this job will ping the Canonical servers telling which
"which" appears twice here

2024-07-25 18:17 UTC, dheyay commented on ubuntu-advantage.1
> +Ubuntu Security Guide is a tool for hardening and auditing and allows for
I think we can reduce the third `and` in this sentence by using something like
```suggestion
Ubuntu Security Guide is a tool for hardening and auditing, allowing for
```

2024-07-25 19:31 UTC, lucasmoura commented
@dheyay updated

2024-07-25 19:34 UTC, dheyay approved these changes
Lgtm

2024-07-26 19:48 UTC, orndorffgrant approved these changes

2024-07-26 19:49 UTC, merged