debian: add more scenarios to dep8 tests
canonical/ubuntu-pro-client pull request #3230
Opened 2024-07-26 15:11 UTC by lucasmoura

## Why is this needed?
We are now calling two API endpoints on the dep8 tests. Those endpoints don't trigger any network call and their main use is to verify if any python3-apt change would change the way we interact with that library, as those API endpoints heavily rely on apt functionality.

## Test Steps
1. Build the package
2. Use the .dsc file to run this command:

```bash
autopkgtest --no-built-binaries --apt-upgrade --setup-commands setup-testbed --shell-fail ubuntu-advantage-tools_1+devel.dsc -- lxd ubuntu-daily:<RELEASE>
```

3. Check that this passes and that the API endpoints appears in the logs 

---

- [ ] *(un)check this to re-run the checklist action*

2024-07-26 16:15 UTC, dheyay requested changes

2024-07-26 16:15 UTC, dheyay commented on debian/tests/usage
> +# This calls are used to unsure that the
Minor nit
```suggestion
# These calls are used to ensure that the
```

2024-07-26 18:14 UTC, lucasmoura commented on debian/tests/usage
> +# This calls are used to unsure that the
Good catch

2024-07-26 18:14 UTC, lucasmoura commented
@dheyay fixed

2024-07-26 18:21 UTC, dheyay approved these changes

2024-07-29 11:16 UTC, renanrodrigo commented
Question: are those two real use case calls enough to call our tests non-superficial? I'd say no, but wonder what you think about it

2024-07-30 13:39 UTC, lucasmoura commented
@renanrodrigo Not at all, the idea is just to collect extra signal here on possible `python3-apt` changes. I have discussed with the team, and even though we agree this is not yet great, it is already an improvement

2024-08-01 17:38 UTC, closed without merging

2024-08-01 17:42 UTC, orndorffgrant commented
sorry - please rebase this on main and reopen