apt: silence warnings when fetching apt-news
canonical/ubuntu-pro-client pull request #3301
Opened 2024-09-11 13:52 UTC by lucasmoura

## Why is this needed?
When fetching the apt-news data, APT will try using the _apt user to store that information on the system. We are now creating a separate folder that is owned by _apt, which silences an APT warning when storing the apt-news data

Fixes: #3209
LP: #2070095

## Test Steps
Check that the APT news related tests are still working and that the error message mentioned on #3209 no longer appears on Noble

---

- [ ] *(un)check this to re-run the checklist action*

2024-09-24 22:23 UTC, orndorffgrant requested changes
As part of our process to get ready for v35, I have rebased `next-v35` onto `main`. As a result, `next-v35` is now obsolete. Please rebase this on `main` and target the PR to `main`.

2024-09-27 19:30 UTC, orndorffgrant approved these changes
This worked in my test - thanks!

2024-09-27 19:30 UTC, orndorffgrant commented on uaclient/defaults.py
> +)
I think this was brought in by mistake during the rebase and can be removed.
```suggestion
```

2024-10-02 16:42 UTC, lucasmoura commented
@orndorffgrant I have fixed the rebase issue

2024-10-02 16:43 UTC, lucasmoura commented
@julian-klode @panlinux If you can also please take a look at this change

2024-10-02 16:59 UTC, julian-klode approved these changes
lgtm

2024-10-04 16:02 UTC, panlinux approved these changes
+1

2024-10-04 19:06 UTC, merged