api: update cache for vulnerabilities
canonical/ubuntu-pro-client pull request #3318
Opened 2024-09-20 17:40 UTC by lucasmoura

## Why is this needed?
We are now caching the vulnerability result as well. That means that if we detect that there is now new vulnerability JSON data to be used and no dpkg related changes on the system, we can simply reuse the old results.

## Test Steps
1. Verify that the vulnerabilities integration tests are still working 
2. Verify that the result cache is being produced
3. Verify when running two API commands in a row, the second one is way faster than the first
---

- [ ] *(un)check this to re-run the checklist action*

2024-09-23 18:55 UTC, renanrodrigo approved these changes

2024-09-23 18:55 UTC, renanrodrigo commented on uaclient/api/u/pro/security/vulnerabilities/_common/v1.py
> +        update_data: bool = True,
heh you did it here

2024-09-23 18:55 UTC, renanrodrigo commented on uaclient/api/u/pro/security/vulnerabilities/_common/v1.py
> +    ) -> Tuple[bool, Optional[datetime.datetime]]:
I would suggest some comment here explaining what is this datetime's meaning

2024-09-24 19:31 UTC, lucasmoura commented
@renanrodrigo updated

2024-09-24 22:24 UTC, orndorffgrant requested changes
As part of our process to get ready for v35, I have rebased `next-v35` onto `main`. As a result, `next-v35` is now obsolete. Please rebase this on `main` and target the PR to `main`.

2024-09-25 18:01 UTC, orndorffgrant reviewed
As discussed, we should document the architecture of these caching mechanisms, when they are used, and when they are invalidated in some kind of dev-docs explanation.

2024-09-25 21:08 UTC, lucasmoura commented
Since we are now adding two more caches, I have created this diagram to simplify the visualization on how those caches are being used:

![image](https://github.com/user-attachments/assets/a7726aef-6bd2-4a4c-be48-c2d3df388850)

2024-09-25 21:54 UTC, lucasmoura commented
@orndorffgrant updated

2024-10-04 19:16 UTC, orndorffgrant approved these changes

2024-10-04 19:18 UTC, merged